; Inno Setup script for the Aadhaar Document Verifier Windows build.
; Produces a single double-click installer (AadhaarVerifier-Setup.exe)
; instead of shipping the raw flutter build folder as a zip.
;
; Installs per-user (no admin/UAC prompt) since CSC operator PCs often
; don't have admin rights on the machine.
;
; Built by CI (see .github/workflows/build-windows.yml) with ISCC.exe,
; which ships preinstalled on GitHub's windows-latest runners. To build
; locally: install Inno Setup (https://jrsoftware.org/isdl.php), run
; `flutter build windows --release` first, then open this file in the
; Inno Setup Compiler (or run `ISCC windows\installer\aadhaar_verifier.iss`
; from the repo root).

#define MyAppName "Aadhaar Document Verifier"
#define MyAppVersion "1.0.0"
#define MyAppPublisher "CSC Aadhaar Verifier"
#define MyAppExeName "aadhaar_verifier.exe"
; Flutter's release output, relative to this .iss file's own folder.
#define ReleaseDir "..\..\build\windows\x64\runner\Release"

[Setup]
AppId={{2F7B6A6B-7B7A-4B6A-9C4B-3A9F7B5E8C21}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
DefaultDirName={localappdata}\Programs\AadhaarVerifier
DefaultGroupName={#MyAppName}
DisableProgramGroupPage=yes
PrivilegesRequired=lowest
ArchitecturesInstallIn64BitMode=x64compatible
OutputDir=..\..\build\installer
OutputBaseFilename=AadhaarVerifier-Setup
Compression=lzma
SolidCompression=yes
UninstallDisplayIcon={app}\{#MyAppExeName}
; Generated by `flutter create` into windows/runner/resources/ - exists
; once the scaffold script (or `flutter create`) has run.
SetupIconFile=..\runner\resources\app_icon.ico

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "Create a &desktop shortcut"; GroupDescription: "Additional icons:"

[Files]
Source: "{#ReleaseDir}\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{group}\Uninstall {#MyAppName}"; Filename: "{uninstallexe}"
Name: "{userdesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "Launch {#MyAppName}"; Flags: nowait postinstall skipifsilent
